[package]
name = "lgogdownloader-tui"
version = "0.1.0"
edition = "2024"
description = "A Ratatui frontend for LGOGDownloader"
license = "WTFPL"

[dependencies]
anyhow = "1"
crossterm = "0.29"
dirs = "6"
ratatui = "0.30.1"
regex = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.9"
zip = "4"

